-- CreateEnum
CREATE TYPE "FundingArea" AS ENUM ('CREATIVE_WORK', 'PERIODICAL', 'EVENT', 'BOOK_PUBLISHING', 'TRANSLATION', 'RESEARCH', 'EDUCATION', 'RECOGNITION', 'OTHER');

-- AlterEnum
ALTER TYPE "AwardSchemeType" ADD VALUE 'OTHER';
