export const validSortableFields = {
    awardDecision: [
        'id',
        'amount',
        'purpose',
        'sourceIdentifier',
        'decisionDate',
        'createdAt',
        'updatedAt',
    ],
    awardScheme: [
        'id',
        'name',
        'type',
        'fundingArea',
        'createdAt',
        'updatedAt',
    ],
    decisionAuthority: [
        'id',
        'name',
        'createdAt',
        'updatedAt',
    ],
    importJob: [
        'id',
        'model',
        'fileName',
        'mimeType',
        'status',
        'totalRows',
        'importedRows',
        'failedRows',
        'startedAt',
        'finishedAt',
    ],
    journal: [
        'id',
        'name',
        'issn',
        'status',
        'format',
        'foundingYear',
        'createdAt',
        'updatedAt',
    ],
    organization: [
        'id',
        'name',
        'website',
        'address',
        'foundingYear',
        'legalForm',
        'sector',
        'createdAt',
        'updatedAt',
    ],
    person: [
        'id',
        'name',
        'birthYear',
        'deathYear',
        'createdAt',
        'updatedAt',
    ],
    sourceDocument: [
        'id',
        'title',
        'url',
        'retrievedAt',
        'createdAt',
        'updatedAt',
    ],
} as const;

export const resourceToSortableEntity = {
    'award-decisions': 'awardDecision',
    'award-schemes': 'awardScheme',
    'decision-authorities': 'decisionAuthority',
    'import-jobs': 'importJob',
    journals: 'journal',
    organizations: 'organization',
    persons: 'person',
    'source-documents': 'sourceDocument',
} as const;

export const validSearchableFields = {
    awardDecision: [
        'purpose',
        'sourceIdentifier',
        'decisionDate',
        'decisionMakerName',
        'recipientName'
    ],
    awardScheme: [
        'name',
        'fundingArea',
    ],
    decisionAuthority: [
        'name',
    ],
    importJob: [
        'model',
        'fileName',
        'mimeType',
        'status',
        'errorMessage',
        'startedAt',
        'finishedAt',
    ],
    journal: [
        'name',
        'issn',
        'status',
        'format',
    ],
    organization: [
        'name',
        'website',
        'address',
        'legalForm',
        'sector',
    ],
    person: [
        'name',
    ],
    sourceDocument: [
        'title',
        'url',
        'retrievedAt',
        'createdAt',
        'updatedAt',
    ],
} as const;